[api]
host = "localhost"
port = 8000
secret_key = "${SECRET_KEY}"

[database]
host = "${DB_HOST|localhost}"
port = "${DB_PORT|1433}"
username = "${DB_USER}"
password = "${DB_PASSWORD}"
database = "${DB_DATABASE|Yandex}"

[logger]
level = "debug"
