version: "3.7"

services:
  yandex_bidder_app:
    container_name: yandex_bidder_app
    build: .
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - 8004:8000
