api:
  host: "0.0.0.0"
  port: 8000
  secret_key: "${SECRET_KEY}"

app:
  concurrency_limit: "${APP_CONCURRENCY_LIMIT|8}"

scheduler:
  time_zone: "UTC"
  suppress_errors_on_startup: true

database:
  host: "${DB_HOST|localhost}"
  port: "${DB_PORT|1433}"
  username: "${DB_USER}"
  password: "${DB_PASSWORD}"
  database: "${DB_DATABASE|Yandex}"

amqp:
  host: "${AMQP_HOST|localhost}"
  port: "${AMQP_PORT|5672}"
  username: "${AMQP_USERNAME}"
  password: "${AMQP_PASSWORD}"
  publishes:
    change_bid:
      exchange:
        name: "change_bid"
        type: "x-delayed-message"
        routing_key: "bid.update"
        args:
          x-delayed-type: "topic"
  consumes:
    updated:
      auto_ack: true
      exchange:
        name: "updated"
        type: "fanout"
        queue:
          name: "updated"
          exclusive: true
          auto_delete: true

logger:
  level: "debug"
