version: "3.7"

networks:
  rabbitmq:
    external: true

services:
  yandex_bidder_app:
    container_name: yandex_bidder_app
    build: .
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./:/app
    networks:
      - rabbitmq
    ports:
      - 8004:8000
